name: PHPStan CI

on:
  repository_dispatch:
    types: [org-workflow-bot]

jobs:
  phpstan:
    name: PHPStan Analysis for ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: SvanBoxel/organization-workflow@main
        with:
          id: ${{ github.event.client_payload.id }}
          callback_url: ${{ github.event.client_payload.callback_url }}
          sha: ${{ github.event.client_payload.sha }}
          run_id: ${{ github.run_id }}
          name: ${{ github.workflow }}
      - uses: AutoModality/action-clean@v1
      - name: Startup
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository.full_name }}
          token: ${{ secrets.ng_token }}
          submodules: true
      - name: Download PHP Release
        uses: dsaltares/fetch-gh-release-asset@1.0.0
        with:
          file: Linux.zip
          repo: NetherGamesMC/php-build-scripts
          version: "tags/8.1"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Unpack PHP Release
        run: unzip Linux.zip && tar -xzvf PHP_Linux-x86_64.tar.gz
      - name: Checkout PharBuilder
        uses: actions/checkout@v3
        with:
          repository: NetherGamesMC/PharBuilder
          token: ${{ secrets.ng_token }}
          path: PharBuilder
      - name: Download Composer
        run: curl -o composer.phar "https://getcomposer.org/composer-stable.phar"
      - name: Add Composer GitHub access token
        run: ./bin/php7/bin/php composer.phar config --global github-oauth.github.com ${{ secrets.ng_token }}
      - name: Install Composer dependencies
        run: ./bin/php7/bin/php composer.phar install --prefer-dist --no-interaction
      - name: Run PHPStan
        run: ./bin/php7/bin/php vendor/bin/phpstan.phar analyze --no-progress
